### ISSUE TITLE
EBS Tagger crashes whenever we add a new non-EBS PVC

### ISSUE THREAD

**Issue by khartahk** [mtougeron/k8s-aws-ebs-tagger#37]
**Describe the bug**
When EBS tagger is running and you add a new EBS volume that it should monitor the pod crashes.

**Expected behavior**
Tagger should discover the new EBS volume and check if it needs to tag it then tag it.

**Error log**
```
E1209 09:18:32.383947       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 65 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1cc9be0, 0x305f4e0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1cc9be0, 0x305f4e0)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc00034cf78, 0xc000000004, 0xc0006c5c28, 0x1, 0x1, 0x0)
    /build/kubernetes.go:253 +0x677
main.watchForPersistentVolumeClaims.func1(0x1f890a0, 0xc00034cf78)
    /build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00005ff60)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006c5f60, 0x22c56c0, 0xc00038e330, 0x1c6d901, 0xc000640000)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005ff60, 0x3b9aca00, 0x0, 0x1, 0xc000640000)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005da380)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000598c30, 0xc000614910)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a24ab7]
goroutine 65 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1cc9be0, 0x305f4e0)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc00034cf78, 0xc000000004, 0xc0006c5c28, 0x1, 0x1, 0x0)
    /build/kubernetes.go:253 +0x677
main.watchForPersistentVolumeClaims.func1(0x1f890a0, 0xc00034cf78)
    /build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00005ff60)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006c5f60, 0x22c56c0, 0xc00038e330, 0x1c6d901, 0xc000640000)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005ff60, 0x3b9aca00, 0x0, 0x1, 0xc000640000)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0005da380)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000598c30, 0xc000614910)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
```

**Comment by mtougeron** [comment]
@khartahk Can you provide the arguments you are passing so I know the configuration the app is running under (e.g., single namespace, multi-namespace, all namespaces)? If possible, how you are setting the tags and the values for them would be useful too (e.g., using default tags and/or PVC specific annotation).

**Comment by khartahk** [comment]
- installed using [helm chart](https://mtougeron.github.io/helm-charts) version: 1.1.5
- we are looking in all namespaces
- the tags are added using PVC specific annotations
- using fsx.csi.aws.com driver

Chart values:
```
fullnameOverride: "k8s-aws-ebs-tagger"
nameOverride: "k8s-aws-ebs-tagger"
podSecurityContext:
  fsGroup: 2000
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
serviceMonitor: true
volumeMounts:
- mountPath: /var/run/secrets/amazonaws.com/serviceaccount/
  name: aws-token
volumes:
- name: aws-token
  projected:
    sources:
    - serviceAccountToken:
        audience: amazonaws.com
        expirationSeconds: 86400
        path: token
```

**Comment by mtougeron** [comment]
I'll look into it soon for you. It shouldn't be evaluating PVCs that are not provisioned by the in-tree or aws-ebs-csi-driver.

**Comment by mtougeron** [comment]
New container image & chart released. Let me know if you have any additional trouble. Thanks again for the bug report!

**Comment by khartahk** [comment]
Updated to image `ghcr.io/mtougeron/k8s-aws-ebs-tagger:v0.0.5` and still have a similar/same error:
```
E1213 10:29:19.356240       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 71 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1cc9d60, 0x30614e0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1cc9d60, 0x30614e0)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc000516528, 0xc000000004, 0xc000155c28, 0x1, 0x1, 0x0)
    /build/kubernetes.go:261 +0x3ff
main.watchForPersistentVolumeClaims.func1(0x1f89140, 0xc000516528)
    /build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00005e760)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000155f60, 0x22c61e0, 0xc0005e2990, 0x1c6db01, 0xc000182de0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005e760, 0x3b9aca00, 0x0, 0x1, 0xc000182de0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000128680)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000fc3e0, 0xc000077160)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a249df]
goroutine 71 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1cc9d60, 0x30614e0)
    /usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc000516528, 0xc000000004, 0xc000155c28, 0x1, 0x1, 0x0)
    /build/kubernetes.go:261 +0x3ff
main.watchForPersistentVolumeClaims.func1(0x1f89140, 0xc000516528)
    /build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00005e760)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000155f60, 0x22c61e0, 0xc0005e2990, 0x1c6db01, 0xc000182de0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00005e760, 0x3b9aca00, 0x0, 0x1, 0xc000182de0)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000128680)
    /go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000fc3e0, 0xc000077160)
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
```

**Comment by mtougeron** [comment]
Okay, I'll dig deeper into this. Sorry for the first fix not being sufficient.

**Comment by khartahk** [comment]
Not a problem. Tnx for taking your time to look into this. If there's anything else I can provide you with I can try to do that.

**Comment by mtougeron** [comment]
Quick update on this, I'm not able to reproduce it in my test cluster but I haven't tried it specifically with fsx csi drivers yet.

**Comment by yurrriq** [comment]
It seems we're (I work with @khartahk) getting nil pointer exceptions for PVCs in a different namespace from the k8s-aws-ebs-tagger Deployment, even when they use the CSI driver.
```
{"level":"info","msg":"Default Tags","tags":{},"time":"2022-01-06T05:29:51Z"}
I0106 05:29:51.842038       1 leaderelection.go:243] attempting to acquire leader lease <k8s-aws-ebs-tagger namespace>/k8s-aws-ebs-tagger...
{"level":"info","msg":"new leader elected: k8s-aws-ebs-tagger-69bb4dd45b-kjqd6","time":"2022-01-06T05:29:51Z"}
I0106 05:30:55.840797       1 leaderelection.go:253] successfully acquired lease <k8s-aws-ebs-tagger namespace>/k8s-aws-ebs-tagger
{"level":"info","msg":"Starting informer","namespace":"","time":"2022-01-06T05:30:55Z"}
{"level":"info","msg":"New PVC Added to Store","namespace":"<k8s-aws-ebs-tagger namespace>","pvc":"<PVC A>","time":"2022-01-06T05:30:55Z"}
{"level":"info","msg":"New PVC Added to Store","namespace":"<k8s-aws-ebs-tagger namespace>","pvc":"<PVC B>","time":"2022-01-06T05:30:55Z"}
{"level":"info","msg":"New PVC Added to Store","namespace":"<k8s-aws-ebs-tagger namespace>","pvc":"<PVC C>","time":"2022-01-06T05:30:55Z"}
{"level":"info","msg":"New PVC Added to Store","namespace":"<a different namespace>","pvc":"<PVC D>","time":"2022-01-06T05:30:55Z"}
E0106 05:30:55.874814       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 44 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1cc9be0, 0x305f4e0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1cc9be0, 0x305f4e0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc0005d6528, 0xc000000004, 0xc0007e9c28, 0x1, 0x1, 0x0)
	/build/kubernetes.go:253 +0x677
main.watchForPersistentVolumeClaims.func1(0x1f890a0, 0xc0005d6528)
	/build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055bf60)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00021ff60, 0x22c56c0, 0xc000206a20, 0x1c6d901, 0xc00017a300)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055bf60, 0x3b9aca00, 0x0, 0x1, 0xc00017a300)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000204280)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00030a290, 0xc0005ca430)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a24ab7]

goroutine 44 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1cc9be0, 0x305f4e0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.processPersistentVolumeClaim(0xc0005d6528, 0xc000000004, 0xc0007e9c28, 0x1, 0x1, 0x0)
	/build/kubernetes.go:253 +0x677
main.watchForPersistentVolumeClaims.func1(0x1f890a0, 0xc0005d6528)
	/build/kubernetes.go:102 +0x24c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:777 +0xc2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055bf60)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00021ff60, 0x22c56c0, 0xc000206a20, 0x1c6d901, 0xc00017a300)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055bf60, 0x3b9aca00, 0x0, 0x1, 0xc00017a300)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000204280)
	/go/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00030a290, 0xc0005ca430)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
```

```yaml
    app.kubernetes.io/version: v0.0.4
    helm.sh/chart: k8s-aws-ebs-tagger-1.1.5
```

**Comment by yurrriq** [comment]
My mistake. The failing PVC above is using the following StorageClass (I'll have to talk to that team about it heh).

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by yurrriq** [comment]
In case it's relevant, here's the IAM Role the ServiceAccount is using:
```json
[
  {
    "Effect": "Allow",
    "Action": [
      "ec2:CreateTags"
    ],
    "Resource": [
      "arn:aws:ec2:*:*:volume/*"
    ],
    "Condition": {
      "StringEquals": {
        "aws:RequestTag/Backup": [
          "<allowed tag value 1>",
          "<allowed tag value 2>"
        ],
        "aws:ResourceTag/kubernetes.io/cluster/<cluster name>": "owned"
      },
      "ForAllValues:StringEquals": {"aws:TagKeys": "<our backup tag>"}
    }
  },
  {
    "Effect": "Allow",
    "Action": [
      "ec2:DeleteTags"
    ],
    "Resource": [
      "arn:aws:ec2:*:*:volume/*"
    ],
    "Condition": {
      "ForAllValues:StringEquals": {"aws:TagKeys": "<our backup tag>"},
      "StringEquals": {
        "aws:ResourceTag/kubernetes.io/cluster/<cluster name>": "owned"
      }
    }
  }
]
```

**Comment by yurrriq** [comment]
Also perhaps noteworthy re: PVC D from above:
```
{"level":"debug","msg":"Does not have aws-ebs-tagger/tags annotation","time":"2022-01-06T05:50:58Z"}
```

**Comment by yurrriq** [comment]
Confirmed same panic with
```yaml
    app.kubernetes.io/version: v0.0.5
    helm.sh/chart: k8s-aws-ebs-tagger-1.2.2
```

**Comment by yurrriq** [comment]
For PVC D and its PV, we've noticed that somehow they have the annotation:
```yaml
volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
```
... even though it's actually `kubernetes.io/aws-ebs`, which explains the panic on https://github.com/mtougeron/k8s-aws-ebs-tagger/blob/v0.0.5/kubernetes.go#L261

**Comment by mtougeron** [comment]
That's what I suspected was happening. By any chance do you have the CSI migration flags enabled? Also, what version of k8s are you running?

**Comment by yurrriq** [comment]
Sorry for the delay. I missed your reply somehow.

> do you have the CSI migration flags enabled?

Yes.

> what version of k8s are you running?

Today, for example, we saw the scenario I described on two clusters running v1.21.7 and one on v1.20.10.

**Comment by mtougeron** [comment]
Thanks for the reply. I think I have enough info now to try and build a duplicating environment. I'll try testing out some fixes in the next few days.

**Comment by yurrriq** [comment]
Awesome, thank you! We do have a couple lab environments where we can test too. Let us know!

**Comment by yurrriq** [comment]
Any luck so far? We've had to remove this from our clusters for the time being unfortunately, but are looking forward to adding it back. Lab clusters are still fair game for testing at any time.

**Comment by mtougeron** [comment]
Sorry for the delay; some work & personal priorities got in the way. I expect to be able to work on it soon. Thanks for your patience.

**Comment by yurrriq** [comment]
Great, thanks for the update!

**Comment by mtougeron** [comment]
Sorry for the delays, I'm still dealing with a family issue. I hope to find time later this week but I can't guarantee that'll happen.

**Comment by yurrriq** [comment]
Please take all the time you need. Family is more important. Thank you for the update. I wish you and yours well.

**Comment by mtougeron** [comment]
@yurrriq @khartahk Can you try version `v0.0.6-beta1`? If that works for you I'll do an official release with the fixes.

**Comment by yurrriq** [comment]
Same error, unfortunately.

**Comment by yurrriq** [comment]
Due to a bug in kOps, we have CSIMigrationAWS enabled but not CSIMigration. Let me try fixing that on our lab cluster...

**Comment by mtougeron** [comment]
arg! I really thought I had this figured out... I'll keep trying.

**Comment by yurrriq** [comment]
I think you might have. I think it's our feature gates that are misconfigured at this point. I should have an answer in maybe half an hour.

**Comment by yurrriq** [comment]
Tried v0.0.6-beta1 again on a kOps 1.22.4 cluster. I had to fix some bad annotations on gp2 volumes, but all appears well now...

**Comment by mtougeron** [comment]
Great! I'll do an official release of v0.0.6 later today

**Comment by mtougeron** [comment]
New release has been published. Thank you for working through this issue.

**Comment by yurrriq** [comment]
Thank for for working with us, and for the new release!
